version: "3.7" # Obsolete but kept for context, can be removed

services:
  nginx:
    build: ./nginx
    container_name: raspi_test_server_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl # Entrypoint writes here
      - ./nginx/logs:/var/log/nginx
      - ./test-data:/usr/share/nginx/html/data:ro
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    depends_on: # Nginx が backend の起動後に開始するようにする
      - backend
    networks: # Nginx と Backend を同じネットワークに入れる
      - test_net
    logging: &logging_defaults # YAML アンカーでログ設定を共通化
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend: # 新しい Flask バックエンドサービス
    build: ./backend # backend ディレクトリの Dockerfile を使う
    container_name: raspi_test_server_backend
    restart: unless-stopped
    volumes:
      # コード変更を即時反映させたい場合はソースをマウント (開発時便利)
      - ./backend:/app
    environment:
      FLASK_APP: app.py # Flask が認識するファイル名
      FLASK_DEBUG: "true" # デバッグモードを有効化 (開発時)
      # 他に必要な環境変数があれば追加
    networks: # Nginx と同じネットワークに参加
      - test_net
    logging: *logging_defaults # Nginx と同じログ設定を使用

networks: # ネットワーク定義
  test_net:
    driver: bridge
    # Optional: Define subnet if needed
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/16